import React, { useState } from 'react';
import { Copy, Play, Download, ArrowLeft, CheckCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';

const SQL = `-- Generated by 10DB Launch
-- Project: my-saas-app
-- Generated at: 2026-05-03 12:00:00 UTC

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT,
  published BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_posts_user_id ON posts(user_id);
CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_user_id ON comments(user_id);`;

function highlight(sql) {
  const keywords = ['CREATE', 'TABLE', 'PRIMARY', 'KEY', 'DEFAULT', 'NOT', 'NULL', 'UNIQUE', 'REFERENCES', 'ON', 'DELETE', 'CASCADE', 'INDEX'];
  const types = ['UUID', 'TEXT', 'BOOLEAN', 'TIMESTAMP', 'INTEGER', 'DECIMAL', 'VARCHAR', 'DATE', 'JSONB'];
  const fns = ['gen_random_uuid()', 'NOW()'];

  return sql.split('\n').map((line, i) => {
    if (line.startsWith('--')) {
      return <div key={i} className="text-muted-foreground/60">{line}</div>;
    }
    const parts = line.split(/(\s+|[(),;])/);
    return (
      <div key={i}>
        {parts.map((part, j) => {
          if (keywords.includes(part.toUpperCase())) return <span key={j} className="text-primary font-semibold">{part}</span>;
          if (types.includes(part.toUpperCase())) return <span key={j} className="text-chart-2">{part}</span>;
          if (fns.some(fn => part.includes(fn.split('(')[0]))) return <span key={j} className="text-chart-3">{part}</span>;
          if (/^'.*'$/.test(part)) return <span key={j} className="text-chart-4">{part}</span>;
          return <span key={j}>{part}</span>;
        })}
      </div>
    );
  });
}

export default function SqlPreview() {
  const [copied, setCopied] = useState(false);

  const copy = () => {
    navigator.clipboard.writeText(SQL);
    setCopied(true);
    toast.success('SQL copied');
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([SQL], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'schema.sql';
    a.click();
    toast.success('Downloaded schema.sql');
  };

  return (
    <div className="flex flex-col h-full overflow-hidden">
      {/* Toolbar */}
      <div className="flex items-center gap-3 px-6 py-3 border-b border-border bg-card shrink-0">
        <Link to="/board" className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-3.5 h-3.5" />
          Board
        </Link>
        <div className="flex-1" />
        <Button size="sm" variant="outline" className="h-7 text-xs" onClick={copy}>
          {copied ? <CheckCheck className="w-3.5 h-3.5 mr-1 text-chart-3" /> : <Copy className="w-3.5 h-3.5 mr-1" />}
          Copy SQL
        </Button>
        <Button size="sm" variant="outline" className="h-7 text-xs" onClick={download}>
          <Download className="w-3.5 h-3.5 mr-1" />
          Download
        </Button>
        <Button size="sm" className="h-7 text-xs bg-primary text-primary-foreground hover:bg-primary/90" onClick={() => toast.success('Schema applied!')}>
          <Play className="w-3.5 h-3.5 mr-1" />
          Apply Schema
        </Button>
      </div>

      {/* Code editor */}
      <div className="flex-1 overflow-auto bg-background">
        <div className="flex">
          {/* Line numbers */}
          <div className="select-none px-4 py-5 text-right border-r border-border bg-card/50">
            {SQL.split('\n').map((_, i) => (
              <div key={i} className="font-mono text-xs text-muted-foreground/40 leading-6">{i + 1}</div>
            ))}
          </div>
          {/* Code */}
          <pre className="flex-1 px-6 py-5 font-mono text-xs text-foreground leading-6 overflow-x-auto">
            {highlight(SQL)}
          </pre>
        </div>
      </div>
    </div>
  );
}